### ISSUE TITLE
Tests failing on Mac

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-cassandra-client#77] opened 2021-10-27 07:48 UTC
When I run the project tests I get these failures:

```
CloseHookTest.testClientClosedAfterUndeploy » AllNodesFailed Could not reach a...
  CloseHookTest.testExternalSharedClientNotClosedAfterUndeploy » AllNodesFailed ...
  SharedTest.testSharedClientNotClosed » AllNodesFailed Could not reach any cont...
  TracingTest.testBoundStatement:132->CassandraClientTestBase.initializeRandomStringKeyspace:91->CassandraClientTestBase.initializeKeyspace:101 » NoNodeAvailable
  TracingTest.testSimpleStatement » AllNodesFailed Could not reach any contact p...
  TracingTest.testSimpleStatementFailure » Timeout
```

**Comment by tsegismont** [comment] 2021-11-17 17:35
Sorry I tried to reproduce but wasn't able to do so (I don't have a working setup on the Mac I have own).

**Comment by Sammers21** [comment] 2022-01-09 09:59
I've reproduced @vietj results and found out that errors starts to occur right after the `AuthenticationTest`, if you would mark it with `@Ignore` annotation, no tests will fail.

**Comment by tsegismont** [comment] 2022-01-10 08:51
@Sammers21 thank you for the update. Do you have an idea about the cause of the issue?

**Comment by Sammers21** [comment] 2022-01-24 13:38
@tsegismont, i dont know how, but it seems like the container is cassandra auth somehow affects the main container we use for tests. I think it does make sense to rework/ignore/remove auth test because it's testing datastax driver auth feature, not the actual code in the repository.

**Comment by tsegismont** [comment] 2022-01-24 14:26
Can we skip it on Mac only? Using junit assume?

Le lun. 24 janv. 2022 à 14:38, Pavel Drankov ***@***.***> a
écrit :

**Comment by vietj** [comment] 2022-01-24 19:48
yes it sounds reasonnable

**Comment by Sammers21** [comment] 2022-01-25 13:16
@tsegismont, yes we can, but that would mean that we will need to stop using the container rule to make sure that the auth container is not started before we run the assumption

**Comment by tsegismont** [comment] 2022-01-26 11:36
https://github.com/vert-x3/vertx-cassandra-client/blob/4ce9633e104e68a16b1cb8d2a8eecfea75ddfe18/src/test/java/io/vertx/cassandra/AuthenticationTest.java#L41-L47

It is a test rule, not a class rule, perhaps the container is not built and started if the assumption is checked in a method annotated with `@BeforeClass`

**Comment by Sammers21** [comment] 2022-01-27 17:09
@tsegismont, sure, make sense.  Can you please check the #78 pull request?

**Comment by Sammers21** [comment] 2022-01-27 17:13
Also @tsegismont, what do you think about adding travis mac os runners? Would it be useful?

**Comment by tsegismont** [comment] 2022-01-28 13:50
>Also @tsegismont, what do you think about adding travis mac os runners? Would it be useful?

@Sammers21 it's not necessary

**Closed** 2022-01-28 16:03 UTC
Labels: bug

**Comment by tsegismont** [comment] 2022-01-31 10:00
Thank you @Sammers21 !
